- name: Install nginx web server
  yum: name=nginx state=installed update_cache=true

- name: Start Nginx
  service: name=nginx enabled=yes state=started

- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  # notify: restart nginx
- name: restart nginx
  service: name=nginx state=restarted enabled=yes 

- name: http service state
  service: name=nginx state=started enabled=yes