- hosts: nginx   
  become: true
  tasks:
    - name: install nginx
      include: nginx.yml

    - name: install php
      include: php.yml

    - name: install wordpress
      include: wordpress.yml

    - name: install mysql
      include: mysql.yml
  
  handlers:
  - name: restart php-fpm
    service: name=php-fpm state=restarted

  - name: restart nginx
    service:
      name: nginx
      state: restarted

  - name: restart php
    service:
      name: php-fpm
      state: restarted
      
    
      
      
      






    


